// Code generated by protoc-gen-go.
// source: proto_error.proto
// DO NOT EDIT!

/*
Package ProtoExample is a generated protocol buffer package.

It is generated from these files:
	proto_error.proto
	proto_example.proto
	proto_id.proto
	proto_session.proto

It has these top-level messages:
	HelloReq
	HelloAck
	InitSessionReq
	InitSessionAck
*/
package ProtoExample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_OK           ErrorCode = 0
	ErrorCode_InvalidParam ErrorCode = 1
)

var ErrorCode_name = map[int32]string{
	0: "OK",
	1: "InvalidParam",
}
var ErrorCode_value = map[string]int32{
	"OK":           0,
	"InvalidParam": 1,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("ProtoExample.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("proto_error.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0x4f, 0x2d, 0x2a, 0xca, 0x2f, 0xd2, 0x03, 0xb3, 0x85, 0x78, 0x02, 0x40, 0x94, 0x6b,
	0x45, 0x62, 0x6e, 0x41, 0x4e, 0xaa, 0x96, 0x2a, 0x17, 0xa7, 0x2b, 0x48, 0xd2, 0x39, 0x3f, 0x25,
	0x55, 0x88, 0x8d, 0x8b, 0xc9, 0xdf, 0x5b, 0x80, 0x41, 0x48, 0x80, 0x8b, 0xc7, 0x33, 0xaf, 0x2c,
	0x31, 0x27, 0x33, 0x25, 0x20, 0xb1, 0x28, 0x31, 0x57, 0x80, 0x31, 0x89, 0x0d, 0xac, 0xd7, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xed, 0x94, 0x75, 0x89, 0x50, 0x00, 0x00, 0x00,
}
