// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: proto_id.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgID int32

const (
	MsgID_TickNtfID           MsgID = 0 // 心跳包
	MsgID_InitSessionNtfID    MsgID = 1 // 外部 客户端 连接服务器用
	MsgID_InitConnectionNtfID MsgID = 2 // 内服 服务器 连接服务器用
	MsgID_HelloReqID          MsgID = 10001
	MsgID_HelloAckID          MsgID = 10002
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:     "TickNtfID",
		1:     "InitSessionNtfID",
		2:     "InitConnectionNtfID",
		10001: "HelloReqID",
		10002: "HelloAckID",
	}
	MsgID_value = map[string]int32{
		"TickNtfID":           0,
		"InitSessionNtfID":    1,
		"InitConnectionNtfID": 2,
		"HelloReqID":          10001,
		"HelloAckID":          10002,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_id_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_proto_id_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_proto_id_proto_rawDescGZIP(), []int{0}
}

var File_proto_id_proto protoreflect.FileDescriptor

var file_proto_id_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x67, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x69, 0x63, 0x6b, 0x4e, 0x74, 0x66, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x74,
	0x66, 0x49, 0x44, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x74, 0x66, 0x49, 0x44, 0x10, 0x02, 0x12, 0x0f,
	0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x49, 0x44, 0x10, 0x91, 0x4e, 0x12,
	0x0f, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x63, 0x6b, 0x49, 0x44, 0x10, 0x92, 0x4e,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x61, 0x74, 0x69, 0x63, 0x61, 0x74, 0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_id_proto_rawDescOnce sync.Once
	file_proto_id_proto_rawDescData = file_proto_id_proto_rawDesc
)

func file_proto_id_proto_rawDescGZIP() []byte {
	file_proto_id_proto_rawDescOnce.Do(func() {
		file_proto_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_id_proto_rawDescData)
	})
	return file_proto_id_proto_rawDescData
}

var file_proto_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_id_proto_goTypes = []interface{}{
	(MsgID)(0), // 0: proto.MsgID
}
var file_proto_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_id_proto_init() }
func file_proto_id_proto_init() {
	if File_proto_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_id_proto_goTypes,
		DependencyIndexes: file_proto_id_proto_depIdxs,
		EnumInfos:         file_proto_id_proto_enumTypes,
	}.Build()
	File_proto_id_proto = out.File
	file_proto_id_proto_rawDesc = nil
	file_proto_id_proto_goTypes = nil
	file_proto_id_proto_depIdxs = nil
}
